// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWgyZaTjO5qT_41COSoFVDKPs-06hfvAw',
    appId: '1:572133181842:web:8c0cf3a1077f5235d1194b',
    messagingSenderId: '572133181842',
    projectId: 'dalel-c6c45',
    authDomain: 'dalel-c6c45.firebaseapp.com',
    storageBucket: 'dalel-c6c45.firebasestorage.app',
    measurementId: 'G-Q3VCCGL3X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp3qlPiD87S5piMlwLL1O1grYwqgDbW-A',
    appId: '1:572133181842:android:62ae369cad41003ed1194b',
    messagingSenderId: '572133181842',
    projectId: 'dalel-c6c45',
    storageBucket: 'dalel-c6c45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEI6du_7wYh1Uxt-F7EsOVeRc3HStlTLY',
    appId: '1:572133181842:ios:82fcae37be839241d1194b',
    messagingSenderId: '572133181842',
    projectId: 'dalel-c6c45',
    storageBucket: 'dalel-c6c45.firebasestorage.app',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEI6du_7wYh1Uxt-F7EsOVeRc3HStlTLY',
    appId: '1:572133181842:ios:82fcae37be839241d1194b',
    messagingSenderId: '572133181842',
    projectId: 'dalel-c6c45',
    storageBucket: 'dalel-c6c45.firebasestorage.app',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWgyZaTjO5qT_41COSoFVDKPs-06hfvAw',
    appId: '1:572133181842:web:af7ef08ca5eee2e8d1194b',
    messagingSenderId: '572133181842',
    projectId: 'dalel-c6c45',
    authDomain: 'dalel-c6c45.firebaseapp.com',
    storageBucket: 'dalel-c6c45.firebasestorage.app',
    measurementId: 'G-WXMRY29ZRC',
  );
}